export const Paths = {
    home: '/',
    signUp: '/sign',
    layout: '/layout',
    project: '/layout/project',
    myPage: '/layout/my-page',
    profileEdit: '/layout/my-page/profile-edit',
    schedule: '/layout/my-page/schedule',
    vacation: '/layout/my-page/vacation',
    teamPage: '/layout/team-page',
    authPage: '/layout/auth-page',
    annualApplication: '/layout/auth-page/annual-application',
    businessReport: '/layout/auth-page/business-report',
    workingOutside: '/layout/auth-page/working-outside',
    mail: '/layout/mail',
    mailWrite: '/layout/mail/mail-write',
    mailRead: '/layout/mail/mail-read',
    sendedMail: '/layout/mail/sended-mail',
} as const;
