export const Paths = {
    home: '/',
    signUp: '/sign',
    project: '/project',
    myPage: '/my-page',
    profileEdit: '/my-page/profile-edit',
    schedule: '/my-page/schedule',
    vacation: '/my-page/vacation',
    teamPage: '/team-page',
    authPage: '/auth-page',
    annualApplication: '/auth-page/annual-application',
    businessReport: '/auth-page/business-report',
    workingOutside: '/auth-page/working-outside',
    mail: '/mail',
    mailWrite: '/mail/mail-write',
    mailRead: '/mail/mail-read',
    sendedMail: '/mail/sended-mail',
} as const;
